---
- name: "[ CephFS ] :: Read Ceph Cluster UUID if it already exists"
  command: "cat {{ fetch_directory }}/ceph_cluster_uuid.conf"
  args:
    removes: "{{ fetch_directory }}/ceph_cluster_uuid.conf"
  delegate_to: localhost
  changed_when: false
  register: cluster_uuid
  check_mode: no
  become: false

- name: "[ CephFS ] :: Copy Ceph Admin keyring"
  copy:
    src: "{{ fetch_directory }}/{{ fsid }}/etc/ceph/{{ cluster }}.client.admin.keyring"
    dest: "/etc/ceph/"
    owner: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    mode: "{{ ceph_keyring_permissions }}"
  when:
    - copy_admin_key
