---

- name: create /etc/ceph directory
  file: path=/etc/ceph state=directory

- name: Add ceph mds hosts to /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_fqdn }}"
    regexp: '^{{ hostvars[item].ansible_default_ipv4.address }}.*'
  with_items: "{{ groups['mdss'] }}"

- name: install cephfs
  apt:
    name: ceph-common
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Create systemd files for cephfs mount if using ldap+automount
  template:
    src: datamount.mount.j2
    dest: "/etc/systemd/system/{{ data_mount_root | regex_replace('^\\/', '') }}.mount"
    mode: 0755
  when: use_ldap_automount
  notify:
    - restart nslcd
    - restart autofs
  register: systemd_template

- meta: flush_handlers
  
- name: Register, Enable, and Start cephfs mount service 
  systemd:
    name: "{{ data_mount_root | regex_replace('^\\/', '') }}.mount"
    state: started
    enabled: yes
    daemon_reload: yes
  when:
    - use_ldap_automount
    - systemd_template is changed

- name: configure /etc/fstab on clients if not using ldap+automount
  mount:
    name: "{{data_mount_root}}"
    src: "{{ groups['mdss'] | join(':6789,') }}:6789:/"
    fstype: ceph
    opts: "defaults"
    state: mounted
  when: not use_ldap_automount
