---
- name: Create CephFS MountConfig Directory
  ansible.builtin.file:
    path: "{{ ceph_mountconfig_directory | default('/opt/ceph') }}"
    state: directory
    owner: "{{ ceph_fs_config_owner }}"
    group: "{{ ceph_fs_config_group }}"
    mode: "{{ ceph_keyring_permissions }}"

- name: Create CephFS Mount-User SecretFile
  ansible.builtin.template:
    src: cephfs_user_secret.j2
    dest: "{{ cephfs_mount.secretfile }}"
    mode: "{{ ceph_keyring_permissions }}"
    owner: "{{ ceph_fs_config_owner }}"
    group: "{{ ceph_fs_config_group }}"
  loop: "{{ cephfs_mounts }}"
  loop_control:
    label: "{{ cephfs_mount.mount }}"
    loop_var: cephfs_mount
  when: (cephfs_mounts | default([])) | length > 0

- name: Create systemd service files for mounting cephfs volumes
  ansible.builtin.template:
    src: datamount.mount.j2
    dest: /etc/systemd/system/{{ cephfs_mount.mount | regex_replace('^\/', '') }}.mount
    mode: "{{ ceph_keyring_permissions }}"
  loop: "{{ cephfs_mounts }}"
  loop_control:
    label: "{{ cephfs_mount.mount }}"
    loop_var: cephfs_mount
  when: (cephfs_mounts | default([])) | length > 0
  register: systemd_template
  tags:
    - cephfs-systemd

- name: Register, enable and start systemd mount service for cephfs volumes. [ldap-autofs]
  ansible.builtin.systemd:
    name: "{{ cephfs_mount.mount | regex_replace('^\\/', '') }}.mount"
    state: "{{ 'restarted' if systemd_template is changed else 'started' }}"
    enabled: true
    daemon_reload: true
  loop: "{{ cephfs_mounts }}"
  loop_control:
    label: "{{ cephfs_mount.mount }}"
    loop_var: cephfs_mount
  when:
    - systemd_template != None
  tags:
    - cephfs-systemd
