---
- name: "Create systemd service files for mounting cephfs volumes. [ldap-autofs]"
  template:
    src: datamount.mount.j2
    dest: "/etc/systemd/system/{{ data_mount_root | regex_replace('^\\/', '') }}.mount"
    mode: 0755
  when: openldap_server_enable_autofs|default(false)
  notify:
    - restart nslcd
    - restart nscd
    - restart autofs
  register: systemd_template

- meta: flush_handlers

- name: "Register, enable and start systemd mount service for cephfs volumes. [ldap-autofs]"
  systemd:
    name: "{{ data_mount_root | regex_replace('^\\/', '') }}.mount"
    state: started
    enabled: yes
    daemon_reload: yes
  when:
    - openldap_server_enable_autofs
    - systemd_template is changed

- name: "Configure cephfs volume mounts in /etc/fstab"
  mount:
    name: "{{data_mount_root}}"
    src: "{% for host in groups['mdss'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}:6789{% if not loop.last %},{% endif %}{% endfor %}:/"
    fstype: ceph
    opts: "defaults"
    state: mounted
  when: not openldap_server_enable_autofs|default(false)
