---
- name: "Create systemd service files for mounting cephfs volumes. [ldap-autofs]"
  template:
    src: datamount.mount.j2
    dest: "/etc/systemd/system/{{ cephfs_mount.mount | regex_replace('^\\/', '') }}.mount"
    mode: 0644
  loop: "{{ cephfs_mounts }}"
  loop_control:
    label: "{{ cephfs_mount.mount }}"
    loop_var: cephfs_mount
  when: cephfs_mounts | length > 0
  notify:
    - restart nslcd
    - restart nscd
    - restart autofs
  register: systemd_template
  tags:
    - cephfs-systemd

- meta: flush_handlers

- name: "Register, enable and start systemd mount service for cephfs volumes. [ldap-autofs]"
  systemd:
    name: "{{ cephfs_mount.mount | regex_replace('^\\/', '') }}.mount"
    state: started
    enabled: yes
    daemon_reload: yes
  loop: "{{ cephfs_mounts }}"
  loop_control:
    label: "{{ cephfs_mount.mount }}"
    loop_var: cephfs_mount
  when:
    - cephfs_mounts | length > 0
    - systemd_template is changed
  tags:
    - cephfs-systemd
