---

- name: create /etc/ceph directory
  file: path=/etc/ceph state=directory

- name: Add ceph mds hosts to /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_fqdn }}"
    regexp: '^{{ hostvars[item].ansible_default_ipv4.address }}.*'
  with_items: "{{ groups['mdss'] }}"

- name: install cephfs
  apt:
    name: ceph-common
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'