---
- name: "Create systemd service files for mounting cephfs volumes. [ldap-autofs]"
  template:
    src: datamount.mount.j2
    dest: "/etc/systemd/system/{{ data_mount_root | regex_replace('^\\/', '') }}.mount"
    mode: 0644
  when: openldap_server_enable_autofs|default(false)
  notify:
    - restart nslcd
    - restart nscd
    - restart autofs
  register: systemd_template
  tags:
    - cephfs-systemd

- meta: flush_handlers

- name: "Register, enable and start systemd mount service for cephfs volumes. [ldap-autofs]"
  systemd:
    name: "{{ data_mount_root | regex_replace('^\\/', '') }}.mount"
    state: started
    enabled: yes
    daemon_reload: yes
  when:
    - openldap_server_enable_autofs
    - systemd_template is changed
  tags:
    - cephfs-systemd
