- name: Create Ceph config directory
  file:
    path: "{{ ceph_conf_directory }}"
    state: directory
    owner: ceph
    group: ceph
  tags:
    - cephfs-confdir
    - cephfs-conf
    - cephfs-keyring

- name: Copy Ceph minimal configuration file
  template:
    src: ceph.conf.j2
    dest: "{{ ceph_conf_directory }}/{{ceph_cluster_name}}.conf"
    mode: 0644
    owner: ceph
    group: ceph
  tags:
    - cephfs-conf
- name: Copy Ceph client keyring
  template:
    src: ceph.client.guest.keyring.j2
    dest: /etc/ceph/ceph.client.guest.keyring
    mode: 0600
    owner: ceph
    group: ceph
  tags:
    - cephfs-keyring