- name: Create Ceph config directory
  file:
    path: "{{ ceph_conf_directory }}"
    state: directory
    owner: "{{ ceph_fs_config_owner }}"
    group: "{{ ceph_fs_config_group }}"
  tags:
    - cephfs-confdir
    - cephfs-conf
    - cephfs-keyring

- name: Copy Ceph minimal configuration file
  template:
    src: ceph.conf.j2
    dest: "{{ ceph_conf_directory }}/{{ceph_cluster_name}}.conf"
    mode: 0644
    owner: "{{ ceph_fs_config_owner }}"
    group: "{{ ceph_fs_config_group }}"
  tags:
    - cephfs-conf

- name: Copy CephFS User Key
  template:
    src: ceph.client.guest.keyring.j2
    dest: "{{ cephfs_user_keyring }}"
    mode: "{{ ceph_keyring_permissions }}"
    owner: "{{ ceph_fs_config_owner }}"
    group: "{{ ceph_fs_config_group }}"
  when:
    - cephx
    - cephfs_copy_user_key
  tags:
    - cephfs-keyring

- name: Copy Ceph client.admin keyring
  template:
    src: ceph.client.admin.keyring.j2
    dest: "{{ ceph_cluster_admin_keyring }}"
    mode: "{{ ceph_keyring_permissions }}"
    owner: "{{ ceph_fs_config_owner }}"
    group: "{{ ceph_fs_config_group }}"
  when:
    - cephx
    - ceph_copy_admin_key
  tags:
    - cephfs-keyring