---


- name: "Install Ceph packages via cephadm"
  block:
    - name: "Download cephadm utility for {{ ceph_stable_release }}"
      ansible.builtin.get_url:
        url: 'https://github.com/ceph/ceph/raw/{{ ceph_stable_release }}/src/cephadm/cephadm'
        dest: "{{ cephadm_path }}"
        mode: '0755'
      tags:
        - cephadm-install
    - name: "Install repository for Ceph {{ ceph_stable_release }}"
      ansible.builtin.command:
        cmd: "{{ cephadm_path }} add-repo --release {{ ceph_stable_release }}"
      tags:
        - cephadm-install
    - name: "Install Ceph packages via cephadm"
      ansible.builtin.command:
        cmd: "{{ cephadm_path }} install {{ item }}"
      loop: "{{ ceph_pkgs }}"
      tags:
        - cephadm-install
  when:
    - ceph_origin == "repository"

