---
- name: Wait for locks
  ansible.builtin.include_tasks:
    file: wait_for_locks.yml

- name: Install Ceph Repository and GPG Key
  when:
    - ansible_os_family == "Debian"
  block:
    - name: Install Ceph repository and gpg key for Debian
      ansible.builtin.deb822_repository:
        name: ceph
        types: deb
        enabled: true
        allow_insecure: true
        state: present
        uris: "{{ ceph_stable_deb_repo }}"
        suites: "{{ ceph_repo_suites | default(ansible_distribution_release) }}"
        components: "{{ ceph_repo_component | default('main') }}"
        signed_by: "{{ ceph_stable_key }}"
      register: ceph_apt_repo_add
      until:
        - ceph_apt_repo_add is not failed
      when:
        - ceph_origin == "repository"

    - name: packages-debian | Update APT Repos # noqa no-handler
      ansible.builtin.apt:
        update_cache: true
      register: cache_updated
      until:
        - cache_updated is not failed

    - name: Install Ceph Packages for Debian
      ansible.builtin.apt:
        name: "{{ ceph_pkgs }}"
        state: "{{ 'latest' if (cephfs_update_packages | default(false)) else 'present' }}"
      register: ceph_dpkg_install
      until: ceph_dpkg_install is not failed

- name: Install Ceph Repository and GPG Key
  when:
    - ansible_os_family == "RedHat"
  block:
    - name: Add repository and key for {{ ceph_release }}
      ansible.builtin.yum_repository:
        name: ceph
        description: Ceph {{ ceph_release }} Repository
        baseurl: "{{ ceph_stable_rpm_repo }}/el{{ ansible_distribution_major_version }}/$basearch"
        gpgkey: "{{ ceph_stable_key }}"
        gpgcheck: true
        state: present
      notify: Update Packages
      when:
        - ceph_origin == 'repository'

    - name: packages-redhat | Update Yum Repos # noqa no-handler
      ansible.builtin.dnf:
        update_cache: true
      register: rpm_cache_updated
      until:
        - rpm_cache_updated is not failed

    - name: Install Ceph Prereq Packages
      ansible.builtin.package:
        name: "{{ ceph_prereq_pkgs }}"
        state: present
      when:
        - ceph_prereq_pkgs | length > 0

    - name: packages-redhat | Update Yum Repos # noqa no-handler
      ansible.builtin.dnf:
        update_cache: true
      register: rpm_cache_updated
      until:
        - rpm_cache_updated is not failed

    - name: Install Ceph Packages on RHEL systems
      ansible.builtin.dnf:
        name: "{{ ceph_pkgs }}"
        state: "{{ 'latest' if (cephfs_update_packages | default(false)) else 'present' }}"
      register: ceph_rpm_install
      until: ceph_rpm_install is not failed
