---
- name: "Install ceph pkgs from os repo"
  ansible.builtin.package:
    name: "{{ ceph_pkgs }}"
    state: present
  when:
    - ceph_origin == "default"
  tags:
    - ceph-os-install

- name: "Install Ceph packages via cephadm"
  block:
    - name: "Download cephadm utility for {{ ceph_stable_release }}"
      get_url:
        url: 'https://github.com/ceph/ceph/raw/{{ ceph_stable_release }}/src/cephadm/cephadm'
        dest: "{{ cephadm_path }}"
        mode: '0755'
      tags:
        - cephadm-install
    - name: "Install repository for Ceph {{ ceph_stable_release }}"
      shell:
        cmd: "{{ cephadm_path }} add-repo {{ ceph_stable_release }}"
      tags:
        - cephadm-install
    - name: "Install Ceph packages via cephadm"
      shell:
        cmd: "{{ cephadm_path }} install {{ ceph_pkgs }}"
      tags:
        - cephadm-install
  when:
    - ceph_origin == "repository"

