---
- name: Install Ceph Repository and GPG Key
  when:
    - ansible_os_family == "Debian"
  block:
    - name: Install Ceph repository and gpg key for Debian
      ansible.builtin.deb822_repository:
        name: ceph
        types: deb
        enabled: true
        trusted: true
        allow_insecure: true
        state: present
        uris: "{{ ceph_stable_deb_repo }}"
        suites: "{{ ceph_repo_suites | default(ansible_distribution_release) }}"
        components: "{{ ceph_repo_component | default('main') }}"
        signed_by: "{{ ceph_stable_key }}"
      register: ceph_apt_repo_add
      notify: update packages
      when:
        - ceph_origin == "repository"

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Install Ceph Packages for Debian
      ansible.builtin.apt:
        name: "{{ ceph_pkgs }}"
        state: "{{ 'latest' if (cephfs_update_packages | default(false)) else 'present' }}"
        update_cache: true
        autoremove: true
        autoclean: true
  rescue:
    - name: Remove Ceph repository
      ansible.builtin.deb822_repository:
        name: ceph
        types: deb
        state: absent

- name: Install Ceph Repository and GPG Key
  when:
    - ansible_os_family == "RedHat"
  block:
    - name: Add repository and key for {{ ceph_release }}
      ansible.builtin.yum_repository:
        name: ceph
        description: Ceph {{ ceph_release }} Repository
        baseurl: "{{ ceph_stable_rpm_repo }}/el{{ ansible_distribution_major_version }}/$basearch"
        gpgkey: "{{ ceph_stable_key }}"
        gpgcheck: true
        state: present
      notify: update packages
      when:
        - ceph_origin == 'repository'

    - name: Install Ceph Prereq Packages
      ansible.builtin.package:
        name: "{{ ceph_prereq_pkgs }}"
        state: present
      when:
        - ceph_prereq_pkgs | length > 0

    - name: Install Ceph Packages on RHEL systems
      ansible.builtin.dnf:
        name: "{{ ceph_pkgs }}"
        state: "{{ 'latest' if (cephfs_update_packages | default(false)) else 'present' }}"
        update_cache: true
        lock_timeout: 300
      register: ceph_pkg_install
      until: ceph_pkg_install is not failed
      retries: 10
      delay: 10
  rescue:
    - name: Remove Ceph repository
      ansible.builtin.yum_repository:
        name: ceph
        state: absent
