---
- name: gather and delegate facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['ceph'] }}"
  run_once: true

- include_tasks: admin_keyring.yml

- include_tasks: cephfs_client.yml
