---
- name: "[ CephFS ] :: Gather facts for all ceph nodes"
  setup:
  delegate_to: localhost
  delegate_facts: True
  with_items: "{{ groups['ceph'] }}"
  when: ansible_lsb.id != "Raspbian"

- import_tasks: cephfs-mount.yml
  when: ansible_lsb.id != "Raspbian"
