---
- name: gather facts from ceph servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['mons'] }}"
  run_once: True

- name: Install Ceph client packages
  block:
    - import_tasks: install.yml
  when:
    - ansible_lsb.id != "Raspbian"
    - not ( ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8" )

- name: Configure Ceph mounts
  block:
    - import_tasks: cephfs-mount.yml
  when:
    - ansible_lsb.id != "Raspbian"
