---
- name: gather facts from ceph servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['mons'] }}"
  run_once: True

- name: Install ceph-common and configure ceph-fs
  block:
    - name: Install ceph-common and supporting packages
      import_tasks: install.yml
    - name: Copy and update Ceph configuration and suppporting files
      import_tasks: configure.yml
    - name: Configure ceph mount options
      import_tasks: cephfs-mount.yml
  when:
    - ansible_lsb.id != "Raspbian"
