---
- name: Gather and delegate facts for Ceph nodes
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['ceph'] | difference(groups.get('clients', [])) }}"
  run_once: true
  when: ansible_lsb.id != "Raspbian"

- import_tasks: cephfs-mount.yml
  when: ansible_lsb.id != "Raspbian"
