---
- name: gather and delegate facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['ceph'] }}"
  when: ansible_lsb.id != "Raspbian"

- include_tasks: cephfs_client.yml
  when: ansible_lsb.id != "Raspbian"
