---
- setup:
- name: "[ CephFS ] :: Gather facts for all ceph nodes"
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['ceph'] }}"
  when: ansible_lsb.id != "Raspbian"

- import_tasks: cephfs_client.yml
  when: ansible_lsb.id != "Raspbian"
