---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always

# - name: Gather facts from ceph servers
#   ansible.builtin.setup:
#   delegate_to: "{{ item }}"
#   delegate_facts: true
#   loop: "{{ groups['mons'] }}"
#   run_once: true
#   tags:
#     - always

- name: Install cephadm, install appropriate repositories and latest packages for mounting cephfs
  when:
    - ansible_distribution != "Raspbian"
    - "'proxmox' not in group_names"
  block:
    - name: Install ceph-common and supporting packages
      ansible.builtin.include_tasks:
        file: install.yml

    - name: Copy and update Ceph configuration and suppporting files
      ansible.builtin.include_tasks:
        file: configure.yml

      tags:
        - cephfs-configure
    - name: Configure ceph mount options
      ansible.builtin.include_tasks:
        file: cephfs-mount.yml

      tags:
        - cephfs-mount
